name: l2rpn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - numpy
  - pandas
  - scipy
  - matplotlib
  - tqdm
  - tensorboard
  - ipykernel
  - pip
  - imageio
  - numba
  - suitesparse
  - pybind11
  - ipywidgets
  - optuna
  - plotly
  - nbformat
  - python-kaleido
  - scienceplots
  - black
  - pip:
      - grid2op
      - l2rpn_baselines
      - lightsim2grid
      - attrs
      - scikit-network==0.32.1
      - torch-geometric==2.5.2
      - pandapower
      - loguru
